#!/bin/bash
url="$1"
if [ -z "$url" ]; then
  read -p "Input YouTube URL: " url
fi
yt-dlp -x --audio-format mp3 --audio-quality 0 \
-o "%(playlist_title)s/%(playlist_index)s - %(title)s.%(ext)s" "$url"
